### ISSUE TITLE
Manual Passes for Kostyantyn (QA Hack Day)

### ISSUE THREAD

**Issue by kjozwiak** [brave/qa-resources#156]
### Per release specialty tests

- [x] Add up to to AC settings - https://github.com/brave/brave-browser/issues/7277
- [x] `Brave Ads has arrived!` notification in BAT icon is shown after browser restart on clean installs #7133 - https://github.com/brave/brave-browser/issues/7133
- [x] reorder items in the App menu #5552 - https://github.com/brave/brave-browser/issues/5552

### Installer

- [x] Check signature: If OS Run `spctl --assess --verbose /Applications/Brave-Browser-Beta.app/` and make sure it returns `accepted`.  If Windows right click on the `brave_installer-x64.exe` and go to Properties, go to the Digital Signatures tab and double click on the signature.  Make sure it says "The digital signature is OK" in the popup window

### Import tests

- [ ] Verify that you can import bookmarks, cookies, history, passwords from Google Chrome 
- [ ] Verify that you can import bookmarks, cookies, history, passwords, autofill and search engines from Firefox
- [ ] Verify that you can import bookmarks from Edge
- [ ] Verify importing `Bookmark HTML` file retains the folder structure on a clean profile

## Extensions/Plugins tests

- [x] Verify PDFJS, Torrent viewer extensions are installed automatically on fresh profile and cannot be disabled
- [x] Verify magnet links and .torrent files loads Torrent viewer page and able to download torrent

### Geolocation

- [x] Check that https://browserleaks.com/geo works and shows correct location

### Crash Reporting

- [x] Check that loading `brave://crash` causes the new tab to crash
- [x] Check that `brave://crashes` lists all the crashes and includes both Crash Report ID & Local Crash ID

### Bravery settings

- [x] Verify that HTTPS Everywhere works by loading http://https-everywhere.badssl.com/
- [x] Turning HTTPS Everywhere off and shields off both disable the redirect to https://https-everywhere.badssl.com/
- [ ] Verify that toggling `Ads and trackers blocked` works as expected
- [ ] Visit https://brianbondy.com/ and then turn on script blocking, page should not load. Allow it from the script blocking UI in the URL bar and it should load the page correctly

### Fingerprint Tests

- [ ] Test that audio fingerprint is blocked at https://audiofingerprint.openwpm.com/ only when `Block all fingerprinting protection` is on

### Rewards

- [ ] Verify you can enable Rewards
- [ ] Verify you are able to exclude a publisher by using the toggle on the Rewards Panel
- [ ] Verify when you click on the BR panel while on a site, the panel displays site specific information (site favicon, domain, attention %)
- [ ] Verify tip panel shows a verified checkmark for a verified publisher/verified YouTube creator
- [ ] Verify tip panel shows a message about unverified publisher
- [ ] Verify BR panel shows message about an unverified publisher
- [ ] Adjust min visit/time in settings. Visit some sites and YouTube channels to verify they are added to the table after the specified settings

### Social-media blocking settings

- [ ] Verify individual `Social media blocking` buttons works as intended when enabled/disabled by visiting https://fmarier.github.io/brave-testing/social-widgets.html

### Tor Tabs

- [ ]  Visit https://check.torproject.org in a Tor window, ensure its shows success message for using a Tor exit node
- [ ]  Visit https://check.torproject.org in a Tor window, note down exit node IP address. Do a hard refresh (Ctrl+Shift+R/Cmd+Shift+R), ensure exit IP changes after page reloads
- [ ]  Visit https://protonirockerxow.onion/ in a Tor window, ensure login page is shown
- [ ]  Visit https://browserleaks.com/geo in a Tor window, ensure location isn't shown

### Session storage

- [ ] Temporarily move away your browser profile and test that a new profile is created when browser is launched 
  - macOS - `~/Library/Application\ Support/BraveSoftware/`
  - Windows - `%userprofile%\appdata\Local\BraveSoftware\` 
  - Linux(Ubuntu) - `~/.config/BraveSoftware/`
- [ ] Test that windows and tabs restore when closed, including active tab
  - [ ] Ensure that the tabs in the above session are being lazy loaded when the session is restored

#### Components
- [ ]  Delete Adblock folder from browser profile and restart browser. Visit `brave://components` and verify `Brave Ad Block Updater` downloads and update the component. Repeat for all Brave components
- [ ] Verify Brave Local Data Updater, Brave Ad Block Updater, Brave Tor Client Updater (Mac), Brave HTTPS Everywhere Updater have non-zero version numbers
