### ISSUE TITLE
Cases for HackDay with Ranjana - August 26th

### ISSUE THREAD

**Issue by kjozwiak** [brave/qa-resources#363]
### `Desktop Cases`

- [x] **`Test #1: Confirm Brave Rewards is using the staging environment`**

Reference: https://github.com/brave/brave-browser/releases

* Launch Brave Nightly using the terminal/command line with these switches:
  - if using macOS: `/Applications/Brave\ Browser\ Nightly.app/Contents/MacOS/Brave\ Browser\ Nightly --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true`
  - if using Windows: `brave.exe --enable-logging=stderr --vmodule=""*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/brave_ads/*"=9" --brave-ads-staging --brave-ads-debug --rewards=staging=true`
  - if using Linux: `brave-browser-nightly --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true`
* Navigate to brave://rewards and enable Brave Rewards
* If you're able to find this URL https://rewards-stg.bravesoftware.com/publishers/prefix-list in the logs, that means that the staging environment is being used and the test passes.

- [x] **`Test #2: Verify you are able to sync open tabs between desktop and mobile`**

* Create a new sync chain on Desktop by visiting `brave://settings/braveSync/setup`
* On Mobile create a sync chain using the QR code from desktop
* Ensure both devices are listed on each device under devices list
* On Desktop, open a new tab and visit `https://buzzfeed.com`
* Right click on the tab and select `Send to your devices` and select mobile device 
* Verify on mobile you receive a notification about the page. Clicking it should open `https://buzzfeed.com` in a new tab

### `Android Cases`

- [x] **`Test #1 - Disabling background images doesn’t show 8 top sites`** - [Reference Issue](https://github.com/brave/brave-browser/issues/12837)

You can download the latest versions of Brave via https://github.com/brave/brave-browser/releases

* Install the latest nightly version of Brave
* Disable background images on NTP via `Settings`
* Find out why you only see 4 favourites/top tiles instead of 8 

- [x] **`Test #2 - IPFS Gateways with Origin isolation`** - [Reference Issue](https://github.com/brave/brave-browser/issues/16999)

You can download the latest versions of Brave via https://github.com/brave/brave-browser/releases

* Install the latest nightly version of Brave or use an existing install from previous test
* Change IPFS public gateway to use `https://dweb.link/`
* Verify no error is shown
* Change IPFS public gateway to use `http://127.0.0.1:48081`
* Verify error is shown

### `Cases if there's still time left`

Following are a few cases that we can run through if we finish going through the above and we still have some time available:

- [ ] **`Ephemeral storage`**

* Run through https://dev-pages.bravesoftware.com/storage/ephemeral-storage.html on `Android` and follow website directions

- [ ] **`brave://settings/ page is empty in Guest window`** - [Reference Issue](https://github.com/brave/brave-browser/issues/17585)

* Download, install, and open 1.30.36 Nightly build using https://github.com/brave/brave-browser/releases
* Open a Guest window
* Navigate to brave://settings 
* Settings page is empty
* Update to latest Nightly version
* Repeat steps 2 and 3
* Confirm settings page is no longer empty
