### ISSUE TITLE
Cases for HackDay with Madhavi - November 30

### ISSUE THREAD

**Issue by kjozwiak** [brave/qa-resources#388]
### `Desktop Cases`

- [x] **`Test #1: Confirm Brave Rewards is using the staging environment`**

Reference: https://github.com/brave/brave-browser/releases

* Launch Brave Nightly using the terminal/command line with these switches:
  - if using macOS: `/Applications/Brave\ Browser\ Nightly.app/Contents/MacOS/Brave\ Browser\ Nightly --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true`
  - if using Windows: `brave.exe --enable-logging=stderr --vmodule=""*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/brave_ads/*"=9" --brave-ads-staging --brave-ads-debug --rewards=staging=true`
  - if using Linux: `brave-browser-nightly --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true`
* Navigate to brave://rewards and enable Brave Rewards
* If you're able to find this URL https://rewards-stg.bravesoftware.com/publishers/prefix-list in the logs, that means that the staging environment is being used and the test passes.

### `iOS Cases`

- [x] **`Test #1: Adding media to playlist from an embedded iFrame `**
Reference issue: [#3923](https://github.com/brave/brave-ios/issues/3923)

* Go to: https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_video
* Change: `<video width="400" controls>` to `<video width="400" controls playsinline>`
* Hit "Run" button.
* Verify you are able to add the video to playlist via long press

- [x] **`Test #2: Add option to disable 'Add to playlist' toolbar button`**
Reference issue: [#4234](https://github.com/brave/brave-ios/issues/4234)

* Look for the settings that disables Add to playlist from URL bar.
* Verify other ways to add items to playlist when its disabled

- [x] **`Test #3: Test import/export bookmark feature`**

* Install and add a few bookmarks and folders/subfolders
* Export the bookmarks to a file 
* Move the file to iPhone storage 
* Uninstall and reinstall the browser
* Import the bookmarks and check if the order is maintained

- [x] **`Test #4: Test adding custom feed to Brave News`**

* Enable Brave News from settings
* Disable all sources. (Figure out how to disable all source at once)
* Go to `Add Source` and enter the following url `https://brave.com/wp-json/wp/v2/pages/27014/`
* Add the custom source and check if you get news feed from Brave
* Delete all the custom sources you added above
* Quit and relaunch the browser
* Verify if you get news feed from Brave

### `Cases if there's still time left`

Following are a few cases that we can run through if we finish going through the above and we still have some time available:

- [ ] **`brave://settings/ page is empty in Guest window`** - [Reference Issue](https://github.com/brave/brave-browser/issues/17585)

* Download, install, and open 1.30.36 Nightly build using https://github.com/brave/brave-browser/releases/v1.30.36
* Open a Guest window
* Navigate to brave://settings 
* Settings page is empty
* Update to latest Nightly version
* Repeat steps 2 and 3
* Confirm settings page is no longer empty

**Comment by kjozwiak** [comment]
Closing as we completed the HackDay 👍
