### ISSUE TITLE
Test Jitsi `8.6.3` SDK beta

### ISSUE THREAD

**Issue by mrose17** [brave/qa-resources#559]
The version of the iOS browser using the Jitsi SDK (in beta) is the following:

```
* Brave build: 0.0 (24.2.15.15)
* BraveCore: 1.63.141 (121.0.6167.139)
```

The release notes are [here](https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md#863-2024-01-22).

Could someone put Brave Talk "through its paces" to see if there are any regressions. The Jitsi folks do a "smoke test", but I'd be happier if we did our own sanity test.

#### Release Date/Target:

* Release Date: N/A (Complete ASAP so `8.6.3` can be added into production TF and released via `1.62.x`)

#### Summary:

We can merge the Jitsi SDK beta into our production build whenever we like, and there are no known issues in the current build, so we are not under a time constraint. 

**Milestone:**

* 1.62` - https://github.com/brave/brave-ios/milestone/123

**Current Progress:** using `Brave build: 0.0 (23.12.8.11)` using `8.6.0 SDK`

* iOS 15--> **`Completed`** via https://github.com/brave/qa-resources/issues/559#issuecomment-1852735920
* iOS 16 --> **`Completed`** via https://github.com/brave/qa-resources/issues/559#issuecomment-1846200463
* iOS 17 --> **`Completed`** via https://github.com/brave/qa-resources/issues/559#issuecomment-1846200463

**Current Progress:** using `Brave build: 0.0 (24.2.15.15)` using `8.6.3 SDK`:

* iOS 15--> **In Progress**
* iOS 16 --> **In Progress**
* iOS 17 --> **In Progress**

**Comment by hffvld** [comment]
### Work in progress...

Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.2
Brave build: 0.0 (23.11.17.19)
BraveCore: 1.61.69 (119.0.6045.124)
Jetsi SDK: 8.6.0
```

**Comment by Uni-verse** [comment]
Verified on `iPhone XR` running `iOS 15.5` using version `0.0 (23.12.8.11)` 

SDK version: 8.6.0

Test Cases: 

- [x] Hosting Brave Talk meeting (Start free call). 
- [x] Joining Brave Talk meeting (brave talk link).
- [x] Inviting via mobile number.
- [x] Toolbar functionality (mic, video, chat, emotes, tile view, 3-dot menu, end call)
- [x] PIP
- [x] Low bandwidth mode
- [x] Car mode
- [x] Brave Talk in background (locked screen)
- [x] Orientation checks

Example | Example | Example | Example 
-|-|-|-
![IMG_0356](https://github.com/brave/qa-resources/assets/17885425/371e024e-74c8-4f42-bf0f-76f248e963c2) | ![IMG_0357 2](https://github.com/brave/qa-resources/assets/17885425/368adb4c-91b0-4ab4-9ea1-271a81785668) | ![IMG_0358 2](https://github.com/brave/qa-resources/assets/17885425/bd137911-3646-4e03-96a9-b93559f3ce4d) | ![IMG_0359 2](https://github.com/brave/qa-resources/assets/17885425/50e0f5bb-38a0-4678-8804-0ead77075dd5)
![IMG_0360 2](https://github.com/brave/qa-resources/assets/17885425/07162a9e-35de-4991-87e7-97a5cf0f1625) | ![IMG_0361 2](https://github.com/brave/qa-resources/assets/17885425/691bd501-708d-4878-a319-5cfbfeaf9d2b) | ![IMG_0362 2](https://github.com/brave/qa-resources/assets/17885425/5740efc2-68cb-49e5-89f2-28cc14a0f65e) | ![IMG_0363 2](https://github.com/brave/qa-resources/assets/17885425/727eef39-818d-4c96-a955-fa7a7f00d274)

**Comment by srirambv** [comment]
Verification passed on on iPad (iOS 16.7.2) and iPhone 13 (iOS 17.2) running `0.0 (23.12.8.11)` using `https://talk. brave.com`
- Verified able create Web3 Talk and join the call
- Verified NFT gating works as expected
- Verified POAP gating works as expected
- Verified BAT gating works as expected
- Verified able to place both ETH/SOL Web3 calls
-----------

Talk Staging doesn't work on the build shows 8x8 webrtc error 
<img width=400 src=https://github.com/brave/qa-resources/assets/17010094/f2309ac6-61fe-4746-b0f3-2975f4e6d971>

Dev environment also doesn't work. Subscription status doesn't update so unable to create a Web3 talk call

**Comment by Uni-verse** [comment]
In progress on `iPhone 12` running `iOS 17` using version `0.0 (24.2.15.15)`

**Comment by hffvld** [comment]
Verified on `iPad Air` running `iOS 16` using version(s):
```
Device/OS: iPad Air / iPadOS 16.7.2
Brave build: 0.0 (24.2.15.15)
BraveCore: 1.63.141 (121.0.6167.139)
Jetsi SDK: 8.6.3
```
---------------------
Tested:
- Start a free call
- Start the call in `Low Bandwith Mode`
- Cancel a call
- Join the existing call
- Chat / Poll
- Raise Your Hand / Reactions
- Enabling/disabling Mic and Camera
- PiP mode
- App idle while on the call
- App in the background while on the call
- Device orientation checks
- Switching views
- Menu and Settings UI

--------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/qa-resources/assets/128532965/d4986ff4-34c1-4e89-9f32-3d7ad1063234) | ![2](https://github.com/brave/qa-resources/assets/128532965/ccdb15f0-5e8e-458f-9c0e-f9ced86ed6fd) | ![3](https://github.com/brave/qa-resources/assets/128532965/edf4daf0-1b8b-4ae9-a000-197b52d6bbc7) |
| ![1](https://github.com/brave/qa-resources/assets/128532965/dac2c899-5481-4d91-8ffe-1d7533f250dc) | ![2](https://github.com/brave/qa-resources/assets/128532965/41e02873-87d6-4a6e-b4e4-8d4235bd76a5) | ![3](https://github.com/brave/qa-resources/assets/128532965/9e24642c-1edb-4e5a-a5c4-2da90c65b377) |
| ![1](https://github.com/brave/qa-resources/assets/128532965/e212c46e-f920-4b08-b89f-ea7fbc6882e4) | ![2](https://github.com/brave/qa-resources/assets/128532965/0c848151-1635-4a1f-9b0a-6d15993d0db7) | ![3](https://github.com/brave/qa-resources/assets/128532965/17c6f837-48cd-4eee-8c8f-4dd662bead72) |
| ![1](https://github.com/brave/qa-resources/assets/128532965/9bb18ab8-e8fb-4a05-8dc0-15297e3289b3) | ![2](https://github.com/brave/qa-resources/assets/128532965/58e45bc5-54bb-4919-af5e-65f23c090118) | ![3](https://github.com/brave/qa-resources/assets/128532965/af7d5b92-0230-4cba-bdd1-1fc7d52088d3) |
| ![1](https://github.com/brave/qa-resources/assets/128532965/565fe993-60df-480c-8f76-53ff508b08f0) | ![2](https://github.com/brave/qa-resources/assets/128532965/e2333f76-2d9d-44e3-a07b-2907fec0ca32) | ![3](https://github.com/brave/qa-resources/assets/128532965/deee3286-2643-412d-9661-44efc6516282) |

**Comment by srirambv** [comment]
Verification passed on iPad with iOS 16.7.5 running `0.0 (24.2.15.15)`
- Verified able to create a Web3 Talk call on Jitsi `8.6.3` build
- Verified able to join a call a Web3 call initiated from other device using the SDK build
- Verified able to sign message when creating call
- Verified able to token gate the calls with POAP/NFT/BAT
- Verified unable to join token gated Web3 talk calls when account doesn't have required tokens/NFTs/POAP

**Comment by kjozwiak** [comment]
@hffvld @Uni-verse @srirambv awesome work guys. Going to close this one off as we're going to be pushing the new SDK via `1.62.1` as per https://github.com/brave/brave-ios/issues/8777#issuecomment-1970055467.
